name: Timeout

on:
  workflow_dispatch: 
jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: nick-fields/retry@v2
      with:
         timeout_seconds: 10
         max_attempts: 3
         command: lap -a
